### ISSUE TITLE
Error running plugin

### ISSUE THREAD

**Issue by geerzo** [AlanFoster/Camelry#52] opened 2013-08-26 16:21 UTC
I just added the plugin to IntelliJ 12 and am now getting this error. I've had to disable the plugin for the IDE to work.

9:19:58 AM PluginException: Error during dispatching of java.awt.event.MouseEvent[MOUSE_RELEASED,(209,500),absolute(209,522),button=1,modifiers=Button1,clickCount=2] on frame3: me/alanfoster/camelry/blueprint/dom/model/BlueprintFileDescription : Unsupported major.minor version 51.0 [Plugin: Camelry]
9:20:06 AM PluginException: Error during dispatching of java.awt.event.MouseEvent[MOUSE_RELEASED,(212,512),absolute(212,534),button=1,modifiers=Button1,clickCount=2] on frame3: me/alanfoster/camelry/blueprint/dom/model/BlueprintFileDescription : Unsupported major.minor version 51.0 [Plugin: Camelry]
9:20:07 AM PluginException: me/alanfoster/camelry/blueprint/dom/model/BlueprintFileDescription : Unsupported major.minor version 51.0 [Plugin: Camelry]: me/alanfoster/camelry/blueprint/dom/model/BlueprintFileDescription : Unsupported major.minor version 51.0 [Plugin: Camelry]

**Comment by AlanFoster** [comment] 2013-08-26 17:05
Hey there,

Sorry you've ran into some issues with the plugin! May I ask what specific JDK/JRE and IntelliJ build number that you are using?

I have been testing with both IntelliJ Ultimate and Community 12.1.4 and JDK 1.7.0_10 and 1.7.0_25;
However I have a set of automated tests that I use to target your specific IntelliJ build and JDK version.

Both of these pieces of information should be available under `Help -> About`

Hopefully it should look something like the following

```
IntelliJ IDEA (Leda) IU-129.1135
JRE: 1.7.0_10
```

Thanks again for posting about your issue! :)

Cheers,
Alan

**Comment by AlanFoster** [comment] 2013-08-26 17:28
I have just double checked the major/minor version for the generated DomFileDescription.class, and it seems IntelliJ has compiled it with the following targets - IE JDK 1.7

```
  minor version: 0
  major version: 51
```

If you're using JDK6, then this would explain the stacktrace you received :)
I'll test this locally with 1.6 and i'll rebuild with a compile target of 1.6 to verify the issue is resolved

If you are able to confirm the specific JDK that you are using that would be a great help :)

Alan

**Comment by geerzo** [comment] 2013-08-26 19:16
I'm on a Mac and the Java Runtime is still 1.6

IntelliJ 12.1.4
Java 1.6.0_51

**Comment by AlanFoster** [comment] 2013-08-26 23:29
Thanks for the confirmation @geerzo!

This should be fixed in 0.1.1, which I hope to release tomorrow - as this is a blocking issue for you :)

Cheers

**Comment by geerzo** [comment] 2013-08-27 02:28
Thanks Alan, can't wait to try it.

**Comment by AlanFoster** [comment] 2013-08-28 09:13
Just letting you know I've now pushed Camelry 0.1.1 to the live plugin repository; You should be able to grab the newest 1.6 compliant classes.

Let me know if you run into any issues, and if you're happy with the release, feel free to close the issue :)

Cheers,
Alan

**Closed as completed** 2013-08-28 18:55 UTC
Labels: bug
